### ISSUE TITLE
Functions titles?

### ISSUE THREAD

**Issue by budparr** [rdwatters/hugo-docs-concept#100]
Hey, @rdwatters No rush on this, but I'm curious why this [title partial](https://github.com/rdwatters/hugo-docs-concept/blob/master/themes/hugo-docs-concept/layouts/partials/page-title.html#L3) is constructed the way it is:

```
{{- if eq .Section "functions" -}}
   {{- replace (.LinkTitle) "and" "<em>and</em>" | safeHTML -}}
{{- else -}}
   {{- .Title | markdownify -}}
{{- end -}}
```
I just don't understand what problem these are trying to solve and why functions have lowercase titles. I also don't see any markdown in other titles. 

Thanks!

**Comment by rdwatters** [comment]
Some lame hackery is my guess that has to do with `title` capitalizing "And". Wrapping it in an emphasis tag allowed for easier styling since I was using the same monospace font for the titles...not sure why I didn't just use a `<span>` though...

**Comment by rdwatters** [comment]
One thing to note is the use of both link titles and title...

I did this intentionally so that I could still sort by title and have it be case insensitive...but I wanted the link title for presentation to keep the casing accurate. It looks like you are using the titles, rather than link titles, here possibly?

http://hugodocs-170421.surge.sh/functions/

**Comment by budparr** [comment]
That's why I found this, investigating the linktitle thing. I don't mind adding that in, just that when I found this I was confused by the replace stuff and the markdownify

**Comment by rdwatters** [comment]
Oh sorry, as for the `markdownify`...I include that in most titles with other projects and probably did it out of habit. Works well for articles for more complex styling, [like here](http://chad.is/beautiful-web-type/#nietzsche), but I guess it offers little for something like the Hugo docs...

**Comment by budparr** [comment]
Right. I use it that way too. No problem.
