### ISSUE TITLE
add Custom Output Types to Home Page

### ISSUE THREAD

**Issue by budparr** [rdwatters/hugo-docs-concept#122]
- [ ] source icon
- [ ] write copy

**Comment by rdwatters** [comment]
Some ideas...

### Headings

1. You're not Limited to HTML
2. Unlimited Output
3. Unlimited Output Formats
4. Generate Any Content You'd Like

(I think the smaller heading just below the icon would be as simple as "Custom Output Formats")

### Descriptions

(I can throw some ideas out there later this evening if you're interested...)

**Comment by budparr** [comment]
sure!

**Comment by rdwatters** [comment]
@budparr I'm good with closing this if you are. (See commit above where copy was tweaked just for usage reasons.)

And thanks again :smile:

**Comment by budparr** [comment]
Perfect, thanks.
