### ISSUE TITLE
Add a page about Upgrading Hugo

### ISSUE THREAD

**Issue by moorereason** [rdwatters/hugo-docs-concept#129]
It would help our users to know exactly how we handle breaking changes and where people should look to make sure they don't miss something.  My thoughts:

1. We only introduce breaking changes in minor releases.
1. When necessary (and possible), we deprecate features for two minor releases.  Deprecation means that warnings are logged when those features are used.
1. We always try to call out deprecations and breaking changes in the `Notes` section of the Release Notes.
1. **Therefore**, always read the `Notes` section of the Release Notes for the major and minor releases.

See https://discuss.gohugo.io/t/upgraded-to-v-0-21-cant-evaluate-field-rsslink/6870

**Comment by rdwatters** [comment]
@moorereason Are you thinking a whole new page under "Getting Started" or that I just write some copy around what I now realize is a pretty pathetic area of the webpage:

https://hugodocs.info/getting-started/installing/#upgrading-hugo

**Comment by moorereason** [comment]
I was thinking of a separate page only because it would be in the menu, but it's your call.

**Comment by rdwatters** [comment]
I think a new page makes the most sense, and for my own notes:

https://github.com/gohugoio/hugo/pull/3620#issuecomment-309866532
