### ISSUE TITLE
Content review: Content Management

### ISSUE THREAD

**Issue by rdwatters** [rdwatters/hugo-docs-concept#139]
Per @bep suggestion to copy edit docs before moving to new Hugo org:

- [ ] archetypes.md
- [ ] authors.md
- [ ] comments.md
- [ ] cross-references.md
- [ ] formats.md
- [ ] front-matter.md
- [ ] menus.md
- [ ] multilingual.md
- [ ] organization.md
- [ ] sections.md
- [ ] shortcodes.md
- [ ] summaries.md
- [ ] taxonomies.md
- [ ] toc.md
- [ ] types.md
- [ ] urls.md

**Comment by bep** [comment]
I'm not following any checklists ... :-)

**Comment by rdwatters** [comment]
> I'm not following any checklists ... :-)

You don't need to. This is mostly for me and my own OCD 😆
