### ISSUE TITLE
Can you close down https://hugodocs.info

### ISSUE THREAD

**Issue by bep** [rdwatters/hugo-docs-concept#144]
Either that or remove the theme that makes it look official, or just let it live on the Netlify domain. People are linking to it and start to think that this is the Hugo docs site, which is bad for several resons -- it kind of takes a little of the firework out of Hugo's upcoming site release.

**Comment by rdwatters** [comment]
How about I take it down and put a single message up saying that we are moving the new site over to https://gohugo.io? I would like to put a date on it as well :smile:

**Comment by bep** [comment]
Never mind. Steve should handle this. I'll focus on the issues in the main repo.
