### ISSUE TITLE
Redistribute existing tutorials and delete the tutorials section

### ISSUE THREAD

**Issue by rdwatters** [rdwatters/hugo-docs-concept#15]
All three of the current tutorials are outdated or better explained elsewhere in the documentation. The real question is whether tutorials should live within the Hugo docs site collection in the first place, or if the best approach is to continue pointing users to external resources in "Press and Articles." For example, the Jekyll community has an [entirely separate site](http://jekyll.tips/), and [Hexo doesn't have any tutorials at all](https://hexo.io/docs/) and [neither does Middleman](https://middlemanapp.com/).

This will have multiple steps:

1. The multilingual tutorial is out of date, but the "Customize Dates" section should be incorporated into `content-management/multilingual` @digitalcraftsman so Golang still doesn't have support for internationalized locale?
2. The "creating a theme" can be removed with parts of it added to /themes/creating/, especially since there are tutorial-specific terms introduced that might confuse users.
3. Migrate from Jekyll can probably be removed entirely but *should* replaced with either new content for the `hugo import jekyll` command (difficult to do since everything under `/commands` is auto-generated or more information added to /developer-tools/migrations/

**Comment by digitalcraftsman** [comment]
> The multilingual tutorial is out of date, but the "Customize Dates" section should be incorporated into content-management/multilingual @digitalcraftsman so Golang still doesn't have support for internationalized locale?

Currently, there is no native support for localized dates, see golang/go#12750. However, there's an attempt to add this feature with a third-party libary (have a look at spf13/hugo#2041).

The workaround isn't as elegant as a template function but it's easy to implement.

> The "creating a theme" can be removed with parts of it added to /themes/creating/, especially since there are tutorial-specific terms introduced that might confuse users.

I agree.

> Migrate from Jekyll can probably be removed entirely but should replaced with either new content for the hugo import jekyll command (difficult to do since everything under /commands is auto-generated.

A short tutorial should be suffiecient with a reference to the list of commands.

**Comment by rdwatters** [comment]
As a heads up, I'm *finally* putting this in the forums with some strict (and hopefully observed) rules  about feedback. I'm sure the community is going to provide some awesome insight that I never would have thought of--as they usually do :smile: Hope you both are having a fantastic weekend.

**Comment by rdwatters** [comment]
Content from original file for Multilingual re: translating months per locale was copied into /content-management/multilingual/. While this issue is closed, a new issue is open for adding more details surrounding Hugo's native Jekyll import feature (/tools/migrations/#jekyll). #24
