### ISSUE TITLE
Improve Search

### ISSUE THREAD

**Issue by budparr** [rdwatters/hugo-docs-concept#151]
An example: "chomp"

<img width="553" alt="screen shot 2017-06-20 at 9 39 56 pm" src="https://user-images.githubusercontent.com/115347/27363194-07497108-5601-11e7-9278-7f868ce8bd5d.png">

results:
https://hugodocs.info/functions/chomp/
https://hugodocs.info/tags/trim/
https://hugodocs.info/categories/functions/
https://hugodocs.info/functions/
https://hugodocs.info/tags/

I don't know anything about Algolia, but I'm guessing there's some way to control this? Perhaps just eliminating any aggregate pages from results, but that's just a guess.

**Comment by rdwatters** [comment]
I think there is a way for us to remove entire sections. Also, I don't think we should have categories writing to the page at all, so I'll change the config.toml. That said, we can configure this via PR. (Looks like Algolia removed the docs concepts index, which is fine; the worst that will happen is we will be a day behind on indexing the site when we get this moved over):

https://github.com/algolia/docsearch-configs/blob/master/configs/hugodocs.json

**Comment by rdwatters** [comment]
Thanks @DirtyF. Good call on @'ing the Algolia folks. 

I think we can take care of it by just disincluding taxonomy pages, which I believe should only includes `/tags` and not `/categories` since the latter provides little value, and I'm going to be cutting the former down considerably...

**Comment by pixelastic** [comment]
Hey all,

Tim from Algolia here. I tried to [access the website](https://hugodocs.info/functions/chomp/) to have a look at the issue but only got a 404-like page.

![image](https://user-images.githubusercontent.com/283419/28177193-4f8bd2de-67fa-11e7-9ea3-e4b1d822fbc3.png)

How can I reproduce the issue? Once you have that, I would ping @ElPicador to have a look at it and/or post a new issue here: https://github.com/algolia/docsearch-configs/issues

**Comment by digitalcraftsman** [comment]
Hello @pixelastic,

thanks for participating in this conversation. For now, you can check out the `dev` branch to see the actual website.

**Comment by rdwatters** [comment]
@digitalcraftsman I believe the index that was set up separately for hugodocs.info has been deleted from Algolia, so in the event that you do run `dev` locally, @pixelastic, the results are probably pulling from the current gohugo.io. Also, @bep is temporarily disabling generation of the tags for the initial release, which I think will help with the repeat results @budparr put in the above screenshot; however, if you think there is a better way to configure the way the results are displayed, that's good too. Thanks.

**Comment by budparr** [comment]
I'm closing this issue. Search seems to be better now that the site has been reindexed. Thanks for your help!
