### ISSUE TITLE
Explanation of what "site is moving" means?

### ISSUE THREAD

**Issue by epatr** [rdwatters/hugo-docs-concept#152]
Is there any explanation of this landing page saying the site is moving? I had just showed it to somebody that was struggling with the official documentation, and then the site stopped working.

**Comment by digitalcraftsman** [comment]
The website was only meant as a temporary demo for the rewritten docs and the application of the new design. It wasn't actually intended to be used by the general public, i.e. regular Hugo users.

Currently, we're working on moving the temporary demo to the official url https://gohugo.io/. But people began to link this site all over the place which caused some users to believe that this were the official docs. At least a few were confused.

Hence we decided to shut the website down and replace it with a landing page. As you can see there are still a few open issues that we've to fix before rolling out the new version of the docs.

@rdwatters it would be great if you could add some clarifications to the text on the landing page.

**Comment by epatr** [comment]
I see. Thanks for responding. It may not have been your intention to be viewed by the general public, but I definitely found immediate use of your site and am disappointed it is gone. It was apparent to me that the site was a work-in-progress, but even in that state it was much more understandable than the official docs.
