### ISSUE TITLE
Make "Getting Started" more friendly

### ISSUE THREAD

**Issue by budparr** [rdwatters/hugo-docs-concept#18]
Just marking this for the moment, but at a glance it seems to me ["Quickstart"](https://github.com/rdwatters/hugo-docs-concept/blob/master/content/getting-started/quick-start.md) is still a bit intimidating, particularly if we're linking to it from the home page (which I was thinking about while working on the design, and I think is a good idea).

Perhaps what's there now could be moved to the tutorials section and something a bit less detailed put it in its place. Worth discussing at any rate.

**Comment by rdwatters** [comment]
Agreed, but duplicative of #17. 

@budparr See also the related thread in the [Hugo issues](https://github.com/spf13/hugo/issues/2864).

Great minds think alike :smile:
