### ISSUE TITLE
Add share button to all single pages

### ISSUE THREAD

**Issue by rdwatters** [rdwatters/hugo-docs-concept#2]
To include 

- Twitter
- YCombinator
- Reddit
- "Copy Link" (for easier sharing)

**Comment by rdwatters** [comment]
@budparr I opened this a bit ago, but maybe it's better to just start with whether this is worthwhile. The headings are already click-copyable, but do you think share buttons add value for docs? If so, I know yours will look better than mine. Thoughts?

**Comment by budparr** [comment]
Hmm. I looked at a couple of examples in the wild and came to no good conclusion.  I think the click-copy headings are super important, so glad you have that. It would be cool if we could come up with a way to share directly the Hugo forums, but maybe that's over thinking it. I think as long as we have good meta-data on the page everything is quite shareable even without the buttons.

**Comment by rdwatters** [comment]
Thanms for digging around. I'm going to close this then. Every page is brimming with metadata, and I like the idea of making it easier to reference directly in the forums too. That's why I did the clickable kinks, but taking it a step further is a good idea...when we have more staff to do so. Cheers.
