### ISSUE TITLE
Toggle for dark/light code theme in all code blocks

### ISSUE THREAD

**Issue by rdwatters** [rdwatters/hugo-docs-concept#27]
Inspired by @moorereason 's preferences *and* Google's documentation:

https://developers.google.com/search/docs/guides/intro-structured-data

In addition to the existing "copy" and "download" buttons in code blocks, users should have the option to toggle between dark and light themes in code blocks. This will likely happen in two parts:

- [ ] Add toggle button to all code blocks and create new sass partial for dark theme (likely [Monokai for Sublime](http://tutsplus.github.io/syntax-highlighter-demos/highlightjs_monokai.html) but with colors tweaked to match Hugo's color palette)
- [ ] Leveraging local storage to persist user preference across pages and sessions

The challenge will be appending this toggle to code blocks that are not currently using `code` shortcode.

**Comment by budparr** [comment]
got it

**Comment by rdwatters** [comment]
Closing. This should be taken care of with @budparr 's new Hugo documentation theme....
