### ISSUE TITLE
Add function signatures

### ISSUE THREAD

**Issue by moorereason** [rdwatters/hugo-docs-concept#31]
Ryan's added a `signature` param in the front matter of the function pages.  Need to populate those params.  The idea is to set the signature to something like this:

```
apply SEQUENCE FUNCTION [PARAM...]

default DEFAULT INPUT

delimit SEQUENCE DELIMITER [LAST]

dict KEY VALUE [KEY VALUE]...

partialCached PARTIAL [CONTEXT [VARIANT]]

slicestr INPUT START [END]

truncate INPUT LENGTH [ELLIPSIS]
```

I started looking at this and ran into some issues with multiple functions in the same file (ie. base64.md and math.md).  I need to think about how this should be structured.

**Comment by rdwatters** [comment]
> base64.md and math.md

I can break up base64, but `math` just seemed ridiculous when I first started creating these individual files.  

I think the `godocref` and `relatedfuncs` are important as well, although pretty tedious since everything here is new.  

`hugoversion` is likely only practicable for future additions...

Speaking of future function additions, I have some ideas, but I'll hold off until after this has been moved into its home under spf13...

**Comment by rdwatters** [comment]
Also, should this be a consideration w/r/t front matter for `funcs` or is this strictly "namespace" in the sense of how it's called on the page? (cf. current docs treatment of [grouping functions into related buckets](http://gohugo.io/templates/functions/))

https://github.com/spf13/hugo/issues/3042

**Comment by moorereason** [comment]
Both.

**Comment by moorereason** [comment]
Related discussion:  https://discuss.gohugo.io/t/5800

**Comment by rdwatters** [comment]
@moorereason While I'm working on content, is there anything I can do to facilitate adding this field/feature to each of the functions pages? E.g. breaking up `base` or `math` a bit more?

**Comment by moorereason** [comment]
Essentially, the `signature` field needs to be an array of strings instead of a just a string.  Example:

```
signature: ["dict KEY VALUE [KEY VALUE]...", "collections.Dict KEY VALUE [KEY VALUE]..."]
```

If we group several functions into a single page (like math), we need to decide whether to use the `signature` field.

**Comment by rdwatters** [comment]
> Essentially, the signature field needs to be an array of strings instead of a just a string.

Done.

> If we group several functions into a single page (like math), we need to decide whether to use the signature field.

I would vote to just keep a couple exceptions and leave these signatures blank...or just add them to the body copy. 

@budparr what do you think about adding this into the theme as part of the function single template ? @moorereason would you be able to add values to a couple of the functions files when you have a chance?

**Comment by moorereason** [comment]
Make me a contributor and assign this issue to me.  I may be able to submit a PR this evening.

**Comment by rdwatters** [comment]
I took it a step further and made you a collaborator 😉 Thanks much for the help @moorereason !
