### ISSUE TITLE
[WIP] Break out last 4 release notes into individual pages...

### ISSUE THREAD

**Issue by rdwatters** [rdwatters/hugo-docs-concept#40]
These *might* live as blog posts in the future. WIP.

See https://github.com/rdwatters/hugo-docs-concept/issues/3

**Comment by rdwatters** [comment]
I thought we were going to talk about content-related items, @budparr. That said, if you want to make the blog posts (or release notes) a separate section of content, please make sure to create the appropriate archetype and add it to the contrib documentation so that creating new files for contribs is only a single command line away. Thanks!

**Comment by budparr** [comment]
Didn't you start this issue? I was just going to do it for you. Totally agree though: we definitely need to talk about this in a bigger picture way. Honestly, my feeling is to get the news section up before the community changes their mind :) so I'm just pushing on it hard right now. And thanks for being patient with me while I feel my way around on contributing to this project. 

Perhaps we should carry on the conversation in the repo I'm working on being that that's where I believe that content would live. Sound good?

**Comment by rdwatters** [comment]
Sure. Can you map this out for me: I mean, how you see these repos working? My assumption was that these docs will just go into the spf13 repo for Hugo, but I know there is talk of creating an organization, which would be great since I can see myself doing tons of changes to the docs even after the new version launches. Also, URL structure: are you thinking that themes, docs, and blog would all be separate now? Directories or subdomains? These are big questions: just trying to get an idea of what you're planning. Thanks Bud!

**Comment by budparr** [comment]
Funny, I didn't walk into this thinking I'd get to make any of these sorts of planning decisions, but, hey, I'm rolling with it, and if it sticks, fine by me, and quite pleased—delighted, actually—if my participation is helpful.

The sub-domain model is currently in place, aside from the docs. It makes sense to me to carry that through.

**repo: hugo**
- Software
- Docs (docs.gohugo.io) _<- that would be a change from the current_

**repo: gohugo.io**
 - home page (gohugo.io) _<- as it is now_
 - news/blog (gohugo.io/TK) _<- new, to be named_

Themes have their own repo, and live at a subdomain, and I see no reason to re-invent that.

**repo: hugoThemes**
- themes (themes.gohugo.io)

To create a continuity across sites, I've pulled the work-so-far on the hugo site into the themes directory, and we can make that one theme for the home/news site, docs, and themes site, using a submodule or NPM to share across the sites. I will consult closely with everyone to make sure the theme represents best practices.

**repo: hugo-theme**
- hugo-theme


I don't know where the forum lives, but noting here that the forum is at `discuss.gohugo.io`

There's also the showcase, but that's a separate conversation.


Those are my thoughts. What do you think?

**Comment by digitalcraftsman** [comment]
> The sub-domain model is currently in place, aside from the docs. It makes sense to me to carry that through.

Continuing the usage of subdomains makes sense I've we want to keep everything consistent. But we should also think about what are the implications for the deployment process. Currently, the theme and main site are two separate websites that life in their own repos.

Unless we try to keep the template code DRY with a flexible theme we'll face the problem that might have to maintain several websites whose codebase is able to partially diverge / being redundant.

**Comment by budparr** [comment]
Netlify's automated deploy process is pretty sweet (Pro plan is free for open source). Other than the forum, I note that the Hugo sites don't have SSL, which is super-easy to implement there. 

As far as theme goes, I think we could adapt the theme I've started for the home site for docs and themes, if that's what you mean about consistency.

**Comment by budparr** [comment]
p.s. I wouldn't normally lobby for a particular commercial service, but hosting is one of those necessarily commercial things, and Netlify is an open-source contributor, a great service, and prominent in the space.

**Comment by rdwatters** [comment]
> I wouldn't normally lobby for a particular commercial service

Neither would I, but my fan-boyism of Netlify has been, well, unabashed. Plus, nobody on this thread will likely ever get a penny from them, so I'm all for it. 👍
