### ISSUE TITLE
Refactor site-navigation.html partial to use Hugo's built-in menu system...

### ISSUE THREAD

**Issue by rdwatters** [rdwatters/hugo-docs-concept#45]
See https://github.com/rdwatters/hugo-docs-concept/issues/44#issuecomment-287566337

Currently, the site navigation is in a `site-navigation.html` partial and pulls from a `sitenavigation.yml` data file. In the interest of dogfooding, this partial should be refactored to leverage Hugo's built-in menu system.

For context, the idea behind deviating from `menu` was that I wanted to make it as easy as possible for creating new content files (esp. functions), and I figured that auto-sorting according to a field in the data file would be easier/faster in future iterations as the site grows.

**Comment by budparr** [comment]
I'm curious to know where this stands. I tried using another theme with the docs site (just to study, really) and the menu didn't work. Are you going to use this [style](https://hugodocs.info/content-management/menus/#advanced):
```
menu:
  main:
    parent: 'extras'
    weight: 20
```

**Comment by rdwatters** [comment]
> I'm curious to know where this stands.

WNYIP. (Work not yet in progress.)

I'm planning on tackling this over the weekend. I used a data file for this partial, so that's why you probably aren't getting the functionality you are expecting. It's also why it's probably so darn slow to build. That said, I'm not a fan of adding the above to individual markdown files. If you're burdening contributors with multiple FM fields, I think it's best to try and stick with metadata that can be exported with the content...

**Comment by rdwatters** [comment]
@budparr If you are working on the site navigation as part of the theme, can we close this?

**Comment by budparr** [comment]
I am, doing "something", but let's leave it for the moment. May need discussion.
