### ISSUE TITLE
Delimiters for YAML and TOML front matter are mixed

### ISSUE THREAD

**Issue by digitalcraftsman** [rdwatters/hugo-docs-concept#5]
The YAML examples on [this page](https://hugodocs.info/content-management/taxonomies/#yaml-front-matter-with-taxonomies-example) use the TOML delimiter `+++`. Instead they should be replaced with `---`.

**Comment by rdwatters** [comment]
Good eye! Thanks, @digitalcraftsman ...and again, good luck on the exams 😄
