### ISSUE TITLE
Copy changes needed for "Hosting on Github Pages"

### ISSUE THREAD

**Issue by BruceEckel** [rdwatters/hugo-docs-concept#54]
In order to get Github pages to properly work, you also need to set the baseURL in your project to the starting page for your Github pages repo.

**Comment by rdwatters** [comment]
@BruceEckel 

Just so I have clarity, can you tell me why this needs to be set? Are you talking about assets breaking (e.g. stylesheets, scripts)?

**Comment by BruceEckel** [comment]
Well, if you don't set the baseURL at all you get the following error when building:
> ERROR 2017/03/27 16:09:04 No 'baseURL' set in configuration or as a flag. Features like page menus will not work without one.

And as far as I can tell, if you don't set the baseURL to your github repo, the links won't work. For example, I had to set mine to:
> baseurl = "https://bruceeckel.github.io/WinterTechForum/"
