### ISSUE TITLE
Change index.html for site to /about in preparation for new news/blog site

### ISSUE THREAD

**Issue by rdwatters** [rdwatters/hugo-docs-concept#56]
In order to treat the new docs as a /docs site with the new design for the homepage and news/blog section, the homepage for the docs should take the end user to the first page of the documentation rather than the homepage (i.e., the list page at /about).

cc/ @budparr

**Comment by budparr** [comment]
I'll be doing this as part of the new theme.

**Comment by rdwatters** [comment]
I was hoping you'd say that :smile: Thanks, @budparr

**Comment by rdwatters** [comment]
Closing this for the above reasons. 👍
