### ISSUE TITLE
Add "tip" admonition to existing "note" and "warning"

### ISSUE THREAD

**Issue by rdwatters** [rdwatters/hugo-docs-concept#59]
@budparr 

This would be easy enough to implement, but I want to open this for discussion first. Bud, I know you are doing considerable leg work right now on the docs theme, so before I add this additional shortcode, I want to make sure it doesn't conflict with your efforts.

### Idea:

We currently have "note" and "warning" admonitions. (Here's the docs on [restructuredText directives](http://docutils.sourceforge.net/docs/ref/rst/directives.html#admonitions) for anyone unfamiliar). Here are the current "semantics":

**note**: A gentle nudge for the reader to pay closer attention to the content called out. Content includes things like contradictions to other areas of the docs (e.g., if a lookup order were to be different for one template type from another) or maybe minor gotchas.  

**warning**: These are bigger concerns; e.g., breaking changes between versions, hard-to-debug gotchas, common mistakes in themes that cause future breaking changes, etc.

### Rationale behind `tip`:

The idea of a "ProTip" is pretty universal and should probably have it's own admonition in the docs. This is a very common tech doc design component that doesn't really fit into either `note` or `warning`.

### Why Bring This Up Now?

If we do add this shortcode, I'd like to start implementing across the site before we go live. I can already think of a few places where this type of callout would come in handy.

### The Good News:

The templating would be identical to `warning` or `note` but with a couple different classes for styling...maybe?

Thoughts?

**Comment by budparr** [comment]
Sounds good to me.
