### ISSUE TITLE
Old and outdated examples

### ISSUE THREAD

**Issue by bep** [rdwatters/hugo-docs-concept#69]
I notice that we still use many of Steve's old examples. While most of them still work, I hope, they look outdated.

One example:

```
  <aside id="meta">
      <div>
      <section>
        <h4 id="date"> {{ .Date.Format "Mon Jan 2, 2006" }} </h4>
        <h5 id="wc"> {{ .FuzzyWordCount }} Words </h5>
      </section>
      <ul id="categories">
        {{ range .Params.tags }}
        <li><a href="{{ $baseURL }}/topics/{{ . | urlize }}">{{ . }}</a> </li>
        {{ end }}
      </ul>
      <ul id="tags">
        {{ range .Params.tags }}
          <li> <a href="{{ $baseURL }}/tags/{{ . | urlize }}">{{ . }}</a> </li>
        {{ end }}
      </ul>
      </div>
  </aside>
```

First: The use of baseURL should be replaced with `absURL`
Second: There is a mistake in there somewhere.

And it should have been written to something like this, totally untested:

```
{{ range $.Site.GetPage("taxonomyTerm", "tags").Pages }}
 <li> <a href="{{ .Permalink }}">{{ .Title}}</a> </li>
{{ end }}
```

**Comment by rdwatters** [comment]
> `{{ range $.Site.GetPage("taxonomyTerm", "tags").Pages }}`
> `<li><a href="{{ .Permalink }}">{{ .Title}}</a> </li>`
> `{{ end }}`

I think the "meta" section is supposed to be specific to the page rather than pull all tags pages---at least from what I can tell from Steve's website.

Updated multiple pieces to reflect newer Hugo features:

https://hugodocs.info/templates/single-page-templates/#project-single-html

Thoughts?
