### ISSUE TITLE
Improve icons and block text on homepage

### ISSUE THREAD

**Issue by rdwatters** [rdwatters/hugo-docs-concept#8]
I have a subscription to flaticons.com that I used for the homepage icons that I then recolored in Affinity Designer. I liked them...for the first 20 minutes. Now I have my misgivings. Also, since they're more complex and directly embedded as SVGs, they're adding additional HTTP requests and killing the PS scores (not the end of the world). 

If anyone can think of some better (svg-based, please) icons...or an image...or whatever...I'm open to it on the homepage.

@budparr @digitalcraftsman @sethmacleod 

Cheers.

**Comment by budparr** [comment]
Are you talking about the blue thing with the pencil in the middle, and the sheets of color on the right?  I'm a bit of a minimalist, but I think that an icon without clear meaning is a decoration at best and a distraction, too, and I can't figure out what they mean. 

And the copy could use some work. For instance "Hugo is the first static site generator fast enough to keep up with your creativity" doesn't sound genuine to me. Then there's are lumps of text below that. 

If you don't mind, I'll take a crack at getting some structure to the page and we can take it from there. Sound good? I should be able to do it over the weekend.

**Comment by rdwatters** [comment]
> I think that an icon without clear meaning is a decoration at best and a distraction, too, and I can't figure out what they mean.

I can't either, really. And @digitalcraftsman in his own polite way, kind of said the same thing to me over Gitter.

> I'll take a crack at getting some structure to the page and we can take it from there.

Sounds good, @budparr. 

I don't know why, but I'm pretty partial to the Gopher. I think only because it took forever to tweak...

**Comment by budparr** [comment]
> I think only because it took forever to tweak...

Ernest Hemingway: "Kill your darlings"

**Comment by budparr** [comment]
actually, I think the gopher is fine.

**Comment by rdwatters** [comment]
> Ernest Hemingway: "Kill your darlings"

We all know how things turned out for Ernie. Haha. Too soon? 

I'd get over deleting the gopher. It seems that the Go community is really big on making Gopherized mascots for their projects [ee gopherize.me](https://gopherize.me/).

As for the copy needing help on the homepage: I agree. It's slop I threw together quickly to make a more conventional homepage. Have at it, but as far as the actual content (docs), I'll be making a few commits a day between now and Sunday with hundreds, if not thousands, of copy edits. That's the time suck for me on this project.

**Comment by ghost** [comment]
I agree re: lightbulb w/pencil. That should be replaced. I don't have a replacement in mind yet, but that would depend on what @budparr comes up with first anyway.

I like the gopher. It's distinctly Hugo.

**Comment by rdwatters** [comment]
No need to keep this open with @budparr 's spiffy new design :smile:
