### ISSUE TITLE
incorrect "title" fields in some TOML example sections

### ISSUE THREAD

**Issue by abathur** [rdwatters/hugo-docs-concept#82]
Some of the TOML front matter example sections have incorrect title fields, perhaps missed in converting between types?

Here are a couple examples: 
https://hugodocs.info/content-management/types/#content/events/my-first-event.md
https://hugodocs.info/content-management/archetypes/#content/posts/post-from-custom-archetype.md

Unrelated, but I noticed while double-checking the above links that the site automagically changes the initial fragment to point the containing section.

**Comment by rdwatters** [comment]
Oops. Closed this here:
https://github.com/rdwatters/hugo-docs-concept/commit/db0b61234d8f9609495d7cb9355358840ae2523e
