### ISSUE TITLE
cf-link next-page on left when there is no cf-link prev-page

### ISSUE THREAD

**Issue by ghost** [rdwatters/hugo-docs-concept#9]
On pages without a previous button, such as `https://hugodocs.info/about/` or `https://hugodocs.info/getting-started/`, the next page button displays on the left side. Presumably it should always be on the right. 

It's fixed by changing:

    #content-footer {
        justify-content: space-between;
    }

to 

    #content-footer {
        justify-content: flex-end;
    }

I know you need `space-between` for when there are both buttons. I'd submit a PR but I'm not set up for your pipeline.

**Comment by rdwatters** [comment]
Good catch @sethmacleod Should be fixed now. Thanks!
