### ISSUE TITLE
Categories?

### ISSUE THREAD

**Issue by budparr** [rdwatters/hugo-docs-concept#95]
I'm curious why all the content has categories that match the section?

**Comment by rdwatters** [comment]
When I originally started this project, I thought it would be a decent future proofing technique and I was playing around with *just* using taxonomies rather than site sections to see how it would work out....

**Comment by budparr** [comment]
So should we take them out?

**Comment by rdwatters** [comment]
Any reason to not keep them in? It's like section metadata that would travel with the document. But if you think it adds clutter, I can take care of it :smile:

**Comment by budparr** [comment]
They're fine (and I'm using them), just as long as they're consistently created. However, I guess my question was why they match Section one-to-one. 

Tags do a good job of rearranging (for lack of a better term) the content to help people find things, and maybe we can utilize categories similarly, but going in the opposite direction. That is, tags pull out specific terms, categories are more general. 

For instance (and I'm not necessarily suggesting this for categories), I've (subtly)  broken the menu into three sections: 

1) Basics (about, getting started, themes)
2) Core (content management, templates, functions, variables, cli)
3) Secondary (troubleshooting, tools, hosting, showcase, contribute)

Again, I'm not suggesting these as categories necessarily, but wondering if we can make categories do more work than replicating sections. What do you think?

p.s. I don't consider this a priority, so feel free to disregard for now if you're busy.

**Comment by rdwatters** [comment]
> Again, I'm not suggesting these as categories necessarily, but wondering if we can make categories do more work than replicating sections. What do you think?

I think this is a great idea and definitely much better use of the taxonomies, to be sure. I think I was just moving stuff around so much in the beginning that they almost served as reminders. We should definitely improve this, but perhaps after launch? 

Aside: you just gave me an idea about how one could use taxonomies (and taxonomic weight) though for menus and completely avoid the whole Hugo menu system :smile:

**Comment by budparr** [comment]
> We should definitely improve this, but perhaps after launch?

Totally fine by me.

**Comment by rdwatters** [comment]
@budparr Since I presume "launch" also includes moving all of this content into it's proper Hugo repo, I'm going to close this issue. Thanks!
